name: build
on: [push]

jobs:
  job:
    name: ${{ matrix.os }}-${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [RelWithDebInfo]

    steps:
      - uses: actions/checkout@v2
          
      - name: Initialise MSVC environment
        if: "contains(matrix.os, 'windows')"
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - uses: lukka/get-cmake@v3.21.1
          
      - name: Build
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          cmake --build build
          cd build
          cpack -G TGZ
          
      - name: Upload output
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-${{ matrix.build_type }}-#${{ github.run_number }}
          path: ${{ github.workspace }}/build/*.tar.gz